sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: qd0vMY5DQIqWyHtEzlK1Oq6cfTS1pQfFbAroiQpLUwrRFRJSM9rCpOynX8kMeM+GnMRGaglxXyBKwpXNMybF2dNiaKqXAV38A4M7YkhKrWZeldxFLh5xv1FA5DgSwPhgbSFb2K+VuRjNstx5mmHIndUMWUrrFBbmyuTbb8WcCWtGNPd5zHJ+ustfd4TdtYlUaew3nVe/DsMawDT+Fo15N6eYl6bfJouejmsw/UARgrECzgcHsD8L+P/Ja3WTZDy+0KAIlKkGbCYPW14UMgocWuLvQgu5QQGAf9wy2NOAMS6/QFC9kcHCOuqt4JLtUlh0SrINZoatKwc9IR57EiE+mmd1RvLtyDCjInk8k7EdZNy2OctNr98zKqMm0RoqdyvCl9YGJUMwRKsJnkBiPG8yQmDfAOYQ92NMT4TB45utjGn2xQEEkRV8ErjW4NQZh2ZKaZLruC9lqrN4+qwwAucMEDSmYcKbbXFRRj+paYBCp+BXfYHfuJd/GZyYEBqONrxH0p4/uWKKdhzD0H700WbS9UWQLkRViQ53cJCL/uAxn+I7oIXpKPyxWCTsa/lRvobIDKxRilgkA0DOG+V4RB2iP3es4eLFSQ2YDqDIxZkNpBFA29EOdVCxtou0q07pf8eLzNtmHZ+lt+B6JbgMODuVpBh5mq+l+MQDaOhoQqN3YMU=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: NPpEzqCrYLeMQvScPFb3GRqnE08G6SM9g3AWz4QPAzhG3/qKSyL7w77QVqNlTH8Sb118fB2VkA/FoT0WBaNyj+eGYNt1WF8J6/6nZiJ5P5CiUdJIo8Vzqx3H94vi8q8wBjP1XZatQ0ANk0GW5iTFDqyLVuEudO3yd5EtczelDgfDt0d+WLvZOKM2KWcWJGYY5aMjeDqXq47DZyLoNaB5TlLcw+kziUirRXB4EOKArTiyDyFT5jzwlPn6dLOfw4PnXBOGb3CEa+5h5WPdUlu68I84A3hC9wGM6Jo6MjEt+XQzcGGqg+UDuSfZXYkv92smneX2+WN4SfQizCDw6TXzTKptXWcSy4DggQV8IMTVkonGPulDM2XJcprgvNk3/jqSZvVUF9sg4wmo6CveWDlRU9gbevATmS/Gun1VuyxsI1GRptFQpG+gzBcfNeWUZ5XmdnWt2DcdyWUkDaNS9Me2TdtB+pD4Gc5UqVqfwaxgZXsiRVjw6AvCLjeoQKHAej5Y21k1d3x2eCz+oHQyae/PVthP2/seU/UJdz9seTHwEQazpC0zqhXt00JdoI3u9uQiJ+BB2MnDuQl6kI+HRkCB27i+4U/2mJg3lq7frlSecCvHYK4P4AA1MK11lFPGDSesLtIln0RQv7xMrCB2a893Ba5hyRyUTIpPpPxS4NzoFZw=
